### ISSUE TITLE
question or feature request

### ISSUE THREAD

**Issue by Benman2785** [i30817/libretro-mkscumm#4]
Hi,

i use Miyoo Mini Plus with Onion OS - it comes with RetroArch

after playing in ScummVM and when i "quit" the game (even if i returned to launcher before ) i get back to RetroArch Menu and have to manually "quit RetroArch"

is there a way to force that automaticly so that i fall back into OnionOS :)

**Comment by i30817** [comment]
That's about the core, ask about it on https://github.com/libretro/scummvm/issues

Might also be about retroarch now that i think about it. Not sure.

**Comment by Benman2785** [comment]
thank you :)
